apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: service-regression-train
  annotations:
    scenarios.ai.sap.com/description: "Service regression train"
    scenarios.ai.sap.com/name: "service-regression-scenario"
    executables.ai.sap.com/description: "Service training executable"
    executables.ai.sap.com/name: "service-ex-regression-exec"
    artifacts.ai.sap.com/text-data.kind: "dataset"
    artifacts.ai.sap.com/text-model-tutorial.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "service-regression"
    executables.ai.sap.com/id: "service-ex-regression"
    ai.sap.com/version: "1.0.0"
spec:
  imagePullSecrets:
    - name: docker-registry-secret
  entrypoint: service-regression-train
  templates:
    - name: service-regression-sk-training
      metadata:
        labels:
          ai.sap.com/resourcePlan: Starter
      inputs:
        artifacts:
          - name: service-regression-data
            path: /app/src/data/
      outputs:
        artifacts:
          - name: service-regression-model
            path: /app/src
            globalName: service-regression-model
            archive:
              none: {}
      container:
        image: "docker.io/msoehn/service-regression-train:0.0.1"
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - >
            set -e && echo "---Start Training---" && python /app/src/TrainData.py && ls -lR /app/src && echo "---End Training---"
